name: education_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  chewie: ^1.7.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  flutter_tindercard:
    git:
      url: https://github.com/NonymousMorlock/flutter_tindercard.git
  equatable: ^2.0.5
  file_picker: ^5.3.3
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  iconly: ^1.0.1
  image_picker: ^1.0.2
  intl: ^0.19.0
  lottie: ^2.6.0
  open_file: ^3.3.2
  path_provider: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.1.12
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  firebase_ui_auth: ^1.6.3
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1
  firebase_auth_mocks: ^0.12.0
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^2.4.1+1
  firebase_storage_mocks: ^0.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
